version: "3.3"

services:
  auto:
    container_name: preservetube-auto
    image: preservetube/auto
    networks:
      - public
    restart: on-failure
    volumes:
      - ./logs:/usr/src/preservetube/auto/logs
      - ./.env:/usr/src/preservetube/auto/.env
      - ./s3.json:/usr/src/preservetube/auto/s3.json

networks:
  public:
    external:
      name: public