version: "3.3"

services:
  auto:
    container_name: preservetube-auto
    image: ghcr.io/preservetube/auto
    networks:
      - public
    restart: on-failure
    volumes:
      - ./.env:/usr/src/preservetube/auto/.env

networks:
  public:
    external: true
    name: public